

import java.util.Locale;
import java.util.Vector;
import javax.swing.*;
import java.text.*;
import java.util.ResourceBundle;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Đỗ Nam
 */
public class CurrencyConverter extends javax.swing.JFrame {
    
    Vector<Locale> vl = new Vector<Locale>();
    String currency[] = {"US Dollar", "EURO", "VND", "Pound"};
    double rate[] = {23000, 26000, 1, 30000};
    Locale locale;
    

    /**
     * Creates new form CurrencyConverter
     */
    public CurrencyConverter() {
        initComponents();
        
        vl.addElement(new Locale("en", "US"));
        vl.addElement(new Locale("it", "IT", "EURO"));
        vl.addElement(new Locale("vi", "VN"));
        vl.addElement(new Locale("en", "GB"));
        
    }
    
    public void ChangeLanguage(){
        ResourceBundle bundle = ResourceBundle.getBundle("Convert", locale);
        this.setTitle(bundle.getString("Currency_Converter"));
        lbEnterAmount.setText(bundle.getString("Enter_Amount"));
        lbSourceCurrency.setText(bundle.getString("Source_Currency"));
        lbTargetCurrency.setText(bundle.getString("Target_Currency"));
        lbConvertedAmount.setText(bundle.getString("Converted_Amount"));
        btnConvert.setText(bundle.getString("Convert"));
        rdEnglish.setText(bundle.getString("English"));
        rdVietnamese.setText(bundle.getString("Vietnamese"));
        pnLang.setBorder(BorderFactory.createTitledBorder
        (BorderFactory.createEtchedBorder(),bundle.getString("Language")));
        
    }
        

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgLanguage = new javax.swing.ButtonGroup();
        lbEnterAmount = new javax.swing.JLabel();
        lbSourceCurrency = new javax.swing.JLabel();
        lbTargetCurrency = new javax.swing.JLabel();
        btnConvert = new javax.swing.JButton();
        lbConvertedAmount = new javax.swing.JLabel();
        txtConvertedAmount = new javax.swing.JTextField();
        txtAmount = new javax.swing.JFormattedTextField();
        cboSource = new javax.swing.JComboBox<>();
        cboTarget = new javax.swing.JComboBox<>();
        pnLang = new javax.swing.JPanel();
        rdEnglish = new javax.swing.JRadioButton();
        rdVietnamese = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbEnterAmount.setText("Enter Amount");

        lbSourceCurrency.setText("Currency Source");

        lbTargetCurrency.setText("Target Currency");

        btnConvert.setText("Convert");
        btnConvert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConvertActionPerformed(evt);
            }
        });

        lbConvertedAmount.setText("Converted Amount");

        txtConvertedAmount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtConvertedAmountActionPerformed(evt);
            }
        });

        txtAmount.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,###.00"))));
        txtAmount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAmountActionPerformed(evt);
            }
        });

        cboSource.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "US Dollar", "EURO", "VND", "Pound" }));

        cboTarget.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "US Dollar", "EURO", "VND", "Pound" }));
        cboTarget.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboTargetActionPerformed(evt);
            }
        });

        pnLang.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Language"));

        bgLanguage.add(rdEnglish);
        rdEnglish.setText("English");
        rdEnglish.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rdEnglishMouseClicked(evt);
            }
        });

        bgLanguage.add(rdVietnamese);
        rdVietnamese.setText("Vietnamese");
        rdVietnamese.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rdVietnameseMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pnLangLayout = new javax.swing.GroupLayout(pnLang);
        pnLang.setLayout(pnLangLayout);
        pnLangLayout.setHorizontalGroup(
            pnLangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnLangLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rdEnglish)
                .addGap(18, 18, 18)
                .addComponent(rdVietnamese)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnLangLayout.setVerticalGroup(
            pnLangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnLangLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnLangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rdEnglish)
                    .addComponent(rdVietnamese))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnLang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnConvert)
                    .addComponent(lbConvertedAmount)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbEnterAmount)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(36, 36, 36)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cboSource, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbSourceCurrency))))
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbTargetCurrency)
                            .addComponent(cboTarget, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(txtConvertedAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnLang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbEnterAmount)
                    .addComponent(lbSourceCurrency)
                    .addComponent(lbTargetCurrency))
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cboSource, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cboTarget, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(btnConvert)
                .addGap(24, 24, 24)
                .addComponent(lbConvertedAmount)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtConvertedAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(193, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtAmountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAmountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAmountActionPerformed

    private void btnConvertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConvertActionPerformed
        // TODO add your handling code here:
        double number;
        if(txtAmount.getText().trim().length() == 0)
        {
            JOptionPane.showMessageDialog(this, "Please enter amount");
            return;
        }
        try{
            NumberFormat nf = NumberFormat.getCurrencyInstance(vl.elementAt(cboTarget.getSelectedIndex()));
            number = Double.parseDouble(txtAmount.getValue().toString()) *
                    rate[cboSource.getSelectedIndex()]/rate[cboTarget.getSelectedIndex()];
            txtConvertedAmount.setText(nf.format(number));
            
        }
        catch(NumberFormatException e){
            JOptionPane.showMessageDialog(this, "Cannot accept characters");
        }
        
    }//GEN-LAST:event_btnConvertActionPerformed

    private void cboTargetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboTargetActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboTargetActionPerformed

    private void rdEnglishMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rdEnglishMouseClicked
        // TODO add your handling code here:
        locale = new Locale("en", "US");
        ChangeLanguage();
    }//GEN-LAST:event_rdEnglishMouseClicked

    private void rdVietnameseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rdVietnameseMouseClicked
        // TODO add your handling code here:
        locale = new Locale("vi", "VN");
        ChangeLanguage();
    }//GEN-LAST:event_rdVietnameseMouseClicked

    private void txtConvertedAmountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtConvertedAmountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtConvertedAmountActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CurrencyConverter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CurrencyConverter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CurrencyConverter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CurrencyConverter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CurrencyConverter().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgLanguage;
    private javax.swing.JButton btnConvert;
    private javax.swing.JComboBox<String> cboSource;
    private javax.swing.JComboBox<String> cboTarget;
    private javax.swing.JLabel lbConvertedAmount;
    private javax.swing.JLabel lbEnterAmount;
    private javax.swing.JLabel lbSourceCurrency;
    private javax.swing.JLabel lbTargetCurrency;
    private javax.swing.JPanel pnLang;
    private javax.swing.JRadioButton rdEnglish;
    private javax.swing.JRadioButton rdVietnamese;
    private javax.swing.JFormattedTextField txtAmount;
    private javax.swing.JTextField txtConvertedAmount;
    // End of variables declaration//GEN-END:variables
}
